applications = [
  # System
  "linux",                       # Kernel
  "linux-firmware",              # Firmware
  "base",                        # Core utilities
  "sddm",                        # Display manager
  "hyprland",                    # Wayland compositor
  "uwsm",                        # Wayland compositor manager
  "xorg-xwayland",               # X11 compatibility layer for Wayland
  "xdg-desktop-portal",          # XDG desktop portal
  "xdg-desktop-portal-hyprland", # XDG desktop portal

  # Shells
  "bash",

  # Key mapper
  "keyd",

  # Fonts
  "ttf-firacode-nerd",

  # CLIs
  "xdg-utils",         # XDG MIME application manager
  "xdg-user-dirs",     # XDG user directory manager
  "wl-clipboard-rs",   # Clipboard manager
  "usage",             # UI toolkit
  "gum",               # Specification for parsing arguments
  "mise",              # Tool version manager
  "git",               # VCS
  "git-absorb",        # Git plugin
  "git-flow-next",     # Git plugin
  "just",              # Command runner
  "chezmoi",           # Dotfile manager
  "zoxide",            # Change directory
  "eza",               # List files
  "bat",               # View files
  "bat-extras",        # Bat utilities
  "fd",                # Find files
  "ripgrep",           # Search files
  "ripgrep-all",       # Ripgrep utilities
  "git-delta",         # Compare files
  "sd",                # Search and replace files
  "choose",            # Extract text from files
  "rust-parallel-bin", # Parse arguments and execute commands
  "pueue",             # Background task executor
  "watchexec",         # File watcher
  "scc-bin",           # Code counter
  "hyperfine",         # Benchmarking
  "procs",             # View running processes
  "ouch",              # Compress and decompress files
  "age",               # Encryption
  "sops",              # Configuration file encryption
  "gojq-bin",          # JSON toolkit
  "taplo",             # TOML toolkit
  "go-yq",             # JSON, TOML, YAML, XML and CSV toolkit
  # TODO: Enable this
  # "precious",          # Linter and formatter
  "lefthook-bin",    # Git hook manager
  "tree-sitter-cli", # Treesitter parser generator
  "xh",              # HTTP client
  "less",            # Pager
  "make",            # Build system
  "gnupg",           # Encryption and signing
  "task",            # To do manager
  "timew",           # Time tracker
  "beanquery",       # Beancount query tool
  "mermaid-cli",     # Diagram as code
  "marp-cli",        # Presentation as code
  "rclone",          # Cloud storage
  "github-cli",      # GitHub client
  "podman",          # Containerization
  "podman-compose",  # Podman plugin
  "colima-bin",      # Containerization
  "docker",          # Containerization
  "docker-compose",  # Docker plugin
  "docker-buildx",   # Docker plugin
  "kubectl",         # Container orchestration
  "helm",            # Kubernetes package manager
  "stern",           # Kubernetes log explorer
  "kubectx",         # Kubernetes context manager
  "kubens",          # Kubernetes namespace manager
  "postgresql",      # SQL database
  "redis",           # Key value database
  "ollama",          # Local LLM manager
  "aider-chat",      # AI agent

  # TUIs
  "fzf",             # Fuzzy finder
  "yazi",            # File system explorer
  "neovim",          # Text editor
  "lazygit",         # Git client
  "zellij",          # Terminal multiplexer
  "bottom",          # System monitor
  "taskwarrior-tui", # Taskwarrior client
  "podman-tui-bin",  # Podman client
  "lazydocker",      # Docker client
  "k9s",             # Kubernetes client
  "opencode-bin",    # AI agent

  # GUIs
  "walker-bin",        # Application launcher
  "elephant-all-bin",  # Application launcher
  "brave-bin",         # Browser
  "browseros-bin",     # Browser
  "xdg-terminal-exec", # Terminal
  "ghostty",           # Terminal
  "waveterm-bin",      # Terminal
  "emacs",             # Text editor
  "zed",               # Text editor
  "void-bin",          # Text editor
  "proton-pass-bin",   # Password manager
  # TODO: Proton drive
  # TODO: Proton VPN

  # WUIs
  "fava", # Beancount client

  # Shell utilities
  "starship",         # Prompt
  "atuin",            # History
  "carapace-bin",     # Autocompletion
  "pay-respects-bin", # Autocorrection

  # Bash
  "bash-language-server", # Language server
  "shellcheck",           # Linter
  "shfmt",                # Formatter

  # Beancount
  "beancount",                 # Linter and formatter
  "beancount-language-server", # Language server

  # Typst
  "typst",

  # Lua
  "lua-language-server", # Language server
  "luacheck",            # Linter
  "stylua",              # Formatter

  # Fennel
  "fennel",
  "fennel-ls", # Language server
  "fnlfmt",    # Formatter

  # Haskell
  "ghc",
  "stack",                   # Version manager, package manager, project manager, command runner and binary installer
  "haskell-language-server", # Language server
  "hlint",                   # Linter
  "haskell-fourmolu",        # Formatter

  # Rust
  "rust",
  "cargo-binstall", # Binary installer
  "rust-analyzer",  # Language server

  # Go
  "go",
  "gopls",       # Language server
  "staticcheck", # Linter
  "gofumpt",     # Formatter
  "delve",       # Debugger
  "mockery-bin", # Mock generator
  "migrate",     # Migration manager

  # JavaScript
  "nodejs",
  "deno",
  "bun-bin",
  "pnpm",    # Version manager, package manager, project manager, command runner and binary installer
  "vite",    # Build tool
  "biome",   # Language server, linter and formatter

  # Python
  "python",
  "uv",     # Version manager, package manager, project manager, command runner and binary installer
  "ty-bin", # Type checker and language server
  "ruff",   # Linter and formatter

  # Protobuf
  "protobuf",
  "protoc-gen-go-bin",      # Go transpiler
  "protoc-gen-go-grpc-bin", # Go transpiler
  "buf",                    # Language server, linter and formatter
]
