# Fennel language server
[".local/share/fennel-ls/docsets/nvim.lua"]
type = "file"
url = "https://git.sr.ht/~micampe/fennel-ls-nvim-docs/blob/main/nvim.lua"

# Emacs package manager
[".config/emacs/elpaca/repos/elpaca"]
type = "git-repo"
url = "https://github.com/progfolio/elpaca.git"
