# Fennel language server
[".local/share/fennel-ls/docsets/nvim.lua"]
type = "file"
url = "https://git.sr.ht/~micampe/fennel-ls-nvim-docs/blob/main/nvim.lua"

# Emacs package manager
[".config/emacs/elpaca/repos/elpaca"]
type = "git-repo"
url = "https://github.com/progfolio/elpaca.git"

# Neovim plugin manager
[".local/share/nvim/lazy/lazy.nvim"]
type = "git-repo"
url = "https://github.com/folke/lazy.nvim.git"

# Doomemacs
[".config/doomemacs"]
type = "git-repo"
url = "https://github.com/doomemacs/doomemacs"
